1. numpy array,shape,reshape

2. Array using arange

In [15]:
import numpy as np
x=np.arange(10)
print(x)

y=np.arange(1,24,2,dtype=float)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23.]


3. Array Comparison using numpy Functions

In [8]:
import numpy as np
x=np.arange(6,60,6)
y=np.arange(3,30,3)
print("First Array:",x)
print("Second Array:",y)

print("x>y")
print(np.greater(x,y))

print("x>=y")
print(np.greater_equal(x, y))
 
print("x<y")
print(np.less(x, y))
 
print("x<=y")
print(np.less_equal(x, y))

print("x=y")
print(np.equal(x,y))

First Array: [ 6 12 18 24 30 36 42 48 54]
Second Array: [ 3  6  9 12 15 18 21 24 27]
x>y
[ True  True  True  True  True  True  True  True  True]
x>= y
[ True  True  True  True  True  True  True  True  True]
x< y
[False False False False False False False False False]
x<= y
[False False False False False False False False False]
x=y
[False False False False False False False False False]


4. Create an array of even numbers between 50 and 90

In [10]:
import numpy as np
x=np.arange(50,90,2)
print("Even Numbers:",x)

Even Numbers: [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


5. To create a 4 * 4 identity matrix

In [12]:
import numpy as np
a=np.identity(4,int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


6. Create a 5*5 zero matrix with elements on the main diagonal 1,2,3,4,5

In [14]:
import numpy as np
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
